### ISSUE TITLE
something is preserved between different feedback popups

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#125]
to reproduce:

* send feedback
* close feedback window
* open feedback window again

![image](https://user-images.githubusercontent.com/3909535/153460615-790ae1f6-f8d5-47fc-9ea4-385110542e24.png)

**Comment by motame** [comment]
Indeed ! It's reproducible.
Fixed in the settings of the corresponding webform:
/mmoda/node/383/webform/configure

For the setting "Redirection location ", instead of "No redirect (reload current page) " the value "Confirmation page".
The previous value is OK when the form is not shown in a modal window.
![mKMb0T3H0G](https://user-images.githubusercontent.com/44972498/192525227-ef89f893-1fa3-40f6-9c51-e6d542e67a0d.png)

Would you please test it on :
https://cdcidev.mtmco.net/mmoda/

**Comment by volodymyrss** [comment]
thanks!
