### ISSUE TITLE
token sent in first request but not in second

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#218]
![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3909535/8d195d96-c9ac-4517-9a0f-409856c421b8)

**Comment by burnout87** [comment]
So I tried to reproduce the issue locally, after having pulled the last changes.

And actually I could reproduce it, with the difference that the token was not included since the first request, but after having flushed the cache, then it worked.

With https://github.com/oda-hub/mmoda-frontend-module/pull/208 the way is retrieved changed, and this is probably the reason why the token was not included within the form.

**Comment by volodymyrss** [comment]
> So I tried to reproduce the issue locally, after having pulled the last changes.
> 
> And actually I could reproduce it, with the difference that the token was not included since the first request, but after having flushed the cache, then it worked.

Drupal cache or browser data?
The thing is that I did both.
In firefox.

> 
> With #208 the way is retrieved changed, and this is probably the reason why the token was not included within the form.

**Comment by burnout87** [comment]
> 
> Drupal cache or browser data? 
> 

Drupal cache

**Comment by volodymyrss** [comment]
> > Drupal cache or browser data?
> 
> Drupal cache

Very weird. I am 100% certain it was cleared with `drush cc`. If this is not done, very few things work.
Can you check if there is a reason the problem is there?

**Comment by burnout87** [comment]
> 
>  Can you check if there is a reason the problem is there?

I have checked for errors in the browser console, noticed what it was going wrong, and after having flushed the drupal cache, it worked.

Did you check the browser console for errors?

**Comment by volodymyrss** [comment]
I did not save any information from the console.

**Comment by motame** [comment]
Cleaning Drupal caches (`drush cc all`) should be enough.
Once done, no need to clean the Browser cache.
All css/js files will be requested by the browser from the server because of the change in the links (string at the end).
Example :
Before
`<script src="https://cdcidev.mtmco.net/mmoda/sites/all/modules/mmoda/js/mmoda.instrument.js?s5lx37"></script>`
After
`<script src="https://cdcidev.mtmco.net/mmoda/sites/all/modules/mmoda/js/mmoda.instrument.js?s5lxkh"></script>`
